site_name: Yo Teams - Microsoft Teams Apps generator
nav:
  - Home: 'index.md'
  - Releases: 'releases.md'
  - Tutorials: 'tutorials.md'
  - Project Structure: 'project-structure.md'
theme:
  name: 'material'
markdown_extensions:
  - admonition
  - codehilite:
     guess_lang: false
  - toc:
      permalink: true
repo_url: https://github.com/pnp/generator-teams
edit_uri: blob/master/docs/docs